# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            pdpd
tagline:          "mugen no ai"
description:      'mental overflow • pictures • research • trials, • errors'
url:              https://universe-7.github.io
baseurl:          /universe-7.github.io/

author:
  name:           'Pete Deevakul'
  url:            https://pdpd.org           

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/universe-7/universe-7.github.io